name: Sync Gitee Repository To Github

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Sync Gitee Repository To Github
      uses: Yikun/hub-mirror-action@master
      with:
        src: gitee/cuc-ccs
        dst: github/YanhuiJessica
        dst_key: ${{ secrets.SYNC_PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_TOKEN }}
        account_type: user
        clone_style: "ssh"
        force_update: true
        mappings: "cs-yanhu1-2021=>CS-YanhuiJessica-2021"
        static_list: "cs-yanhu1-2021"